title: 'No Name Box'
logo: '/user/images/gus_nnblogo.png'
default_lang: en
author:
  name: 'Agustí Montes'
  email: amontes@nnbox.org
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
